### ISSUE TITLE
Please post some builds

### ISSUE THREAD

**Issue by andybak** [juniorxsound/ReTouch#2]
I'd be happy to give it a go but nearly every time I try and use a project from Github that requires compiling I end up wasting a fair amount of time with inscrutable errors before giving up.

And I've got access to Mac and Linux boxes - which at least have a snowball in hell's chance of a successful build. If all I had access to was a Windows box then I wouldn't even try.

**Comment by juniorxsound** [comment]
Hi @andybak,

I understand your frustration.

This project is actually very straightforward to build thanks to the inclusion of all dependencies as git submodules, just make sure to clone it using the ```--recursive``` flag (see [instructions section](https://github.com/juniorxsound/ReTouch#installation) for full command)

If you still prefer a binary I have uploaded a macOS release which you can download [here](https://github.com/juniorxsound/ReTouch/releases/tag/0.0.1)

Thanks
